[package]
name = "magicians-server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.48", features = ["rt", "rt-multi-thread", "macros", "signal"] }
axum = { version = "0.8", features = ["ws"] }
tower-http = { version = "0.6", features = ["cors", "trace"] }
rust-embed = "8.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.18", features = ["serde", "v4"] }
mime_guess = "2.0"